### ISSUE TITLE
Seems to be broken?

### ISSUE THREAD

**Issue by MrCoolGuy640** [ILoveAppleJuice/pet-simulator99-autofish#2]
Hi there I tried to run it, but I got this happened, it wouldn't do anything when I enabled it, spat out some 0's in console, then threw an error.

I had roblox open, then ran it, the window opened and all, then I sat in the fishing area with my mouse over the water waiting for a bit and nothing happened (this is after I clicked to enable on the Tkinter window.) so then I switched back to cmd and then it spat out some 0's and an error. Not sure if I have the incorrect device size or something wierd.

Here's the output, if you could take a quick look for me I'd appreciate it :)

`0
0
0
0
0
0
0
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\mrcoo\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1962, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\mrcoo\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 861, in callit
    func(*args)
  File "c:\Users\mrcoo\OneDrive\Desktop\Programs\PetSimPyProgram\program.py", line 135, in main_loop
    if not get_focused_window_title() == "Roblox" or not get_window_under_cursor() == "Roblox":
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\mrcoo\OneDrive\Desktop\Programs\PetSimPyProgram\program.py", line 24, in get_window_under_cursor
    window = gw.getWindowsAt(x, y)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrcoo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygetwindow\_pygetwindow_win.py", line 142, in getWindowsAt
    if pointInRect(x, y, window.left, window.top, window.width, window.height):
                         ^^^^^^^^^^^
  File "C:\Users\mrcoo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygetwindow\__init__.py", line 149, in left
    return self._rect.left
           ^^^^^^^^^^^^^^^
  File "C:\Users\mrcoo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyrect\__init__.py", line 296, in left
    self.onRead(LEFT)
  File "C:\Users\mrcoo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygetwindow\__init__.py", line 54, in _onRead
    r = self._getWindowRect()
        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrcoo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygetwindow\_pygetwindow_win.py", line 199, in _getWindowRect
    _raiseWithLastError()
  File "C:\Users\mrcoo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygetwindow\_pygetwindow_win.py", line 99, in _raiseWithLastError
    raise PyGetWindowException('Error code from Windows: %s - %s' % (errorCode, _formatMessage(errorCode)))
pygetwindow.PyGetWindowException: Error code from Windows: 1400 - Invalid window handle.`

**Comment by MrCoolGuy640** [comment]
Issue no longer relevant
